version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world
      - run:
          name: Print the current time
          command: date
